pl_trainer:
  max_epochs: 50
  devices:
  - 0
  accelerator: gpu
  precision: 16
  log_every_n_steps: 10

# should match arguments in the BrainPatchesDataModule class
dataset:
  train_num_workers: 2
  train_batch_size: 5
  val_num_workers: 2
  val_batch_size: 5
  reshape_size: 200
# should match arguments in the module class
model:
  net: efficient # densenet, efficient (for b7), resnet
  # n_classes: 4
  # in_channels: 2
  # feature_scale: 4
  loss: cross_entropy # 
  optimizer_class: adam
  learning_rate: 0.01

exp_name: efficientb0-pretrained-lr0.01_da02_lrsch_no_earlystop
