pl_trainer:
  max_epochs: 400
  devices:
  - 0
  accelerator: gpu
  precision: 16
  log_every_n_steps: 5

training:
  early_stopping:  False
  monitor_ckpt: val_loss # val_acc, val_f1, val_auroc
  display_recons: True

dataset:
  train_batch_size: 5
  val_batch_size: 5
  train_num_workers: 2
  val_num_workers: 2
  reshape_size: 120
  map_type: 
    # - MTsat
    # - R1
    - R2s_WLS1
    # - PD_R2scorr
  random_state: 42
  masked: brain_masked 
  shuffle: True

# should match arguments in the module class
model:
  net: resnet_monai #
  projection_dim: 64
  temperature: 0.5 # 0.05
  channels:
    - 32
    - 64
    - 128
    # - 256
    # - 512
  latent_size: 128
  in_channels: 1
  loss: l1kld # l1, mse, l1kld
  gamma: 0.9
  optimizer_class: sgd # 
  learning_rate: 0.001
  sch_patience: 0
  momentum: 0 # 0.9  
  weight_decay: 0 # 0.0001    

exp_name: rs120_ssl_simclr_resnet_DA02_bs5_v2epochs400
