pl_trainer:
  max_epochs: 50
  devices:
  - 0
  accelerator: gpu
  precision: 16
  log_every_n_steps: 10

# should match arguments in the BrainPatchesDataModule class
dataset:
  train_num_workers: 2
  train_batch_size: 5
  val_num_workers: 2
  val_batch_size: 5
  reshape_size: 200
  random_state: 42

# should match arguments in the module class
model:
  net: efficient # monai: densenet, efficient (for b7), resnet
  n_classes: 2
  in_channels: 1
  loss: focal # dice, cross_entropy, bin_cross_entropy, focal, tversky
  optimizer_class: sgd
  learning_rate: 0.01
  sch_patience: 10

exp_name: efficientb0-da00_lrsch_focal_sgd0.01_rs42
